apiVersion: v1
kind: Namespace
metadata:
 name: k8s-training

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: k8s-training
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: quay.io/gauravkumar9130/myweb
        name: fbweb
        stdin: true
        tty: true
